// The C-bindings generated by bindgen will be placed here.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)] // this is important as the generated bindings might be more than what we use

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
